# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.

commands:
  print_pipeline_id:
    description: "Print the id of the pipeline"
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID

orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1

# Orchestrate or schedule a set of jobs
jobs:
  print_hello:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run: echo "hello"

  print_world:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run: echo "world"

  test_env_vars:
    docker:
      - image: cimg/base:2021.04
        environment:
          NAME: "David Essien"
    steps:
      - run: echo "my name is $NAME"
  
  save_hello_world_output:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run: echo "text to output here" > output.txt
      - persist_to_workspace:
          root: .
          paths:
            - .
  
  print_output_file:
    docker:
      - image: cimg/base:2021.04

    steps:
      - attach_workspace:
          at: .
      - run: cat output.txt

  get_pipeline_id:
    docker:
      - image: cimg/base:2021.04
    steps:
      - print_pipeline_id

  failing:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run: exit 1
      - run:
          name: on error
          command: echo "Hello Error!"
          when: on_fail

workflows:
  # Name the workflow "welcome"
  welcome:
    jobs:
      - welcome/run
      - print_hello
      - print_world:
          requires:
            - print_hello
      - test_env_vars:
          requires:
            - print_world
      - save_hello_world_output:
          requires:
            - test_env_vars
      - print_output_file:
          requires:
            - save_hello_world_output
      - get_pipeline_id:
          requires:
            - print_output_file
      - failing

